language: node_js
node_js:
- 9
env:
  global:
    secure: aS01tlimPhTDDD+VzJRf2N1YHru6DEBtkGw+9sZ9ULj4rQ7GfwLzUZPZ1ft7alVzaxJdDZEvcjSkroG64kXAsnD2/UzsUez1ON5xd1zOoEv8C6X13kE7grtZ9bZ0qzg5H8S/P+lxnWI6BS4vpzNRb7Z3st5TSEYaM5twTkDY22k1hXTscFez4yvpqEifJGzgdPdKvzWocl+TXuvLyZWHK+VeVcbQEom1RaH2lPvx48kjvLWr13pt3+qDS7i0DbQHHwcUSUVs41OOHByUehlpR0vRC7IAW/W6qxzanm078zkTzgZypmlQUI7ELz/ruIKhAqziEkE9Y7p0mSmP16YFW3IpJF+4QcPGIfzT+KMHK3XBAsYQXvBI0HN2ItbruDYRsHtbVwcyXiOWAOBHYg+9jJmZCIt7Uu5bywmOuR1Z+z95F150fSuIGFX+Oz/9y6HiiaiT/rYKAcRekc6HDBe8iEjNSH6/WtcbcIcvzeK3TCiUmmNjLjtdWlo/p8YuCzMNzZsVkAsRq34KrHVH4svzMrdjJdNENFGrmK/YDgx9ulWCItlrasUMvUwXd0BvrRP31hpaWMDJaKLlJo6ehEWY7tqTAE3aWLKSYUAewk8+qUiq28QwGeVnmU1uJGVPHdqSu+scgbakLpItIXji0rnLHtBh2VDV5a6VJnKBwKs7FA4=
install:
- yarn
- lerna bootstrap
- lerna run build
script:
- yarn test
- (cd example && yarn build)
- (cd example && PORT=3000 yarn serve &)
- (cd example && yarn e2e --verbose)
deploy:
  provider: script
  skip_cleanup: true
  script: bin/publish.sh
  on:
    branch: master
